"""P2 transaction domain, SQLite authority, UoW and Flush boundary."""

from .domain import (
    DomainMutation,
    DomainTransitionError,
    archive_transaction,
    begin_delegate,
    complete_transaction,
    consume_delegate,
    delete_transaction,
    fail_transaction,
    invalidate_activation,
    open_activation,
    pause_transaction,
    restore_transaction,
)
from .predicates import (
    is_execution_closed,
    is_live_record,
    is_match_candidate,
    is_open_continue,
    is_paused,
    is_permanently_closed,
    is_runnable_record,
    is_waiting_delegate,
    project_compat_status,
)
from .effects import EffectCoordinator, acceptance_effect_id_for_delegate
from .flush import FlushCoordinator
from .schedule import (
    OneShotScheduleRun,
    ScheduleDeliveryStatus,
    ScheduleRunStatus,
    ScheduleTransitionError,
    ScheduleTransitionResult,
    TransactionScheduleCoordinator,
    stable_schedule_delivery_id,
    stable_schedule_run_id,
)
from .store import (
    IdempotencyConflictError,
    RecordNotFoundError,
    RevisionConflictError,
    RuntimeStoreError,
    SQLiteRuntimeStore,
    StaleClaimError,
    StoreInvariantError,
)
from .uow import RuntimeUnitOfWork

__all__ = [
    "DomainMutation",
    "DomainTransitionError",
    "EffectCoordinator",
    "FlushCoordinator",
    "IdempotencyConflictError",
    "OneShotScheduleRun",
    "RecordNotFoundError",
    "RevisionConflictError",
    "RuntimeStoreError",
    "RuntimeUnitOfWork",
    "ScheduleDeliveryStatus",
    "ScheduleRunStatus",
    "ScheduleTransitionError",
    "ScheduleTransitionResult",
    "SQLiteRuntimeStore",
    "StaleClaimError",
    "StoreInvariantError",
    "TransactionScheduleCoordinator",
    "acceptance_effect_id_for_delegate",
    "archive_transaction",
    "begin_delegate",
    "complete_transaction",
    "consume_delegate",
    "delete_transaction",
    "fail_transaction",
    "invalidate_activation",
    "is_execution_closed",
    "is_live_record",
    "is_match_candidate",
    "is_open_continue",
    "is_paused",
    "is_permanently_closed",
    "is_runnable_record",
    "is_waiting_delegate",
    "open_activation",
    "pause_transaction",
    "project_compat_status",
    "restore_transaction",
    "stable_schedule_delivery_id",
    "stable_schedule_run_id",
]
