from memory.build_memory.build_episode import scan_and_build_episodes
from memory.build_memory.qualify_episode import scan_and_qualify_episodes
from memory.build_memory.filter_episode import scan_and_filter_episodes
from memory.build_memory.build_scene import scan_and_build_scene, scan_now_scene
scan_and_build_episodes()
scan_and_qualify_episodes()
scan_and_filter_episodes()
scan_now_scene()
scan_and_build_scene()