# E-mail QQ email
Email:
  Acount : 
  Password :
  url: "imap.gmail.com"
  conclude_prompt: "用简洁的语言总结一下以下的邮件内容：\n{}"

Gmail:
  url: "imap.gmail.com"
  Acount: "changshengEVA@gmail.com"
  Password: "odlratkmfvritenm"
  conclude_prompt: "请对以下邮件内容进行总结：{}"
