#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Macro event search workflow.

Searches scene files by cosine similarity on `theme_embedding`.
"""

import json
import logging
import math
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


def search_macro_events(
    query: Dict[str, Any],
    scene_dir: Path,
    embed_func: Callable[[str], List[float]],
    use_threshold: bool = True,
    threshold: float = 0.7,
    topk: int = 10,
) -> Dict[str, Any]:
    """
    Search macro events (scene) by `theme_embedding`.

    Query format:
    - Prefer: {"theme_embedding": [float, ...]}
    - Fallback: {"theme": "..."} (embedding will be generated by embed_func)
    """
    mode = "threshold" if bool(use_threshold) else "topk"
    safe_threshold = _safe_float(threshold, default=0.7)
    safe_topk = _safe_int(topk, default=10, minimum=1)

    result: Dict[str, Any] = {
        "hit": False,
        "mode": mode,
        "threshold": safe_threshold,
        "topk": safe_topk,
        "total_scene_count": 0,
        "matched_count": 0,
        "results": [],
    }

    if not isinstance(query, dict):
        logger.warning("search_macro_events: query is not a dict")
        return result

    query_embedding = _get_query_embedding(query=query, embed_func=embed_func)
    if not query_embedding:
        logger.warning("search_macro_events: query embedding is empty")
        return result

    if not scene_dir.exists() or not scene_dir.is_dir():
        logger.warning("search_macro_events: scene_dir not found: %s", scene_dir)
        return result

    scene_files = sorted(scene_dir.glob("*.json"))
    result["total_scene_count"] = len(scene_files)

    candidates: List[Dict[str, Any]] = []
    for scene_file in scene_files:
        scene_data = _load_scene_file(scene_file)
        if not scene_data:
            continue

        scene_embedding = _get_scene_theme_embedding(scene_data=scene_data, embed_func=embed_func)
        if not scene_embedding:
            continue

        similarity = _cosine_similarity(query_embedding, scene_embedding)
        candidates.append(
            {
                "scene_id": scene_data.get("scene_id") or scene_file.stem,
                "scene_file": scene_file.name,
                "similarity": float(similarity),
                "theme": scene_data.get("theme", ""),
                "diary": scene_data.get("diary", ""),
                "source": scene_data.get("source", {}),
                "meta": scene_data.get("meta", {}),
            }
        )

    candidates.sort(key=lambda x: x["similarity"], reverse=True)

    if mode == "threshold":
        filtered = [c for c in candidates if c["similarity"] >= safe_threshold]
    else:
        filtered = candidates[:safe_topk]

    result["results"] = filtered
    result["matched_count"] = len(filtered)
    result["hit"] = len(filtered) > 0
    return result


def _get_query_embedding(
    query: Dict[str, Any],
    embed_func: Callable[[str], List[float]],
) -> Optional[List[float]]:
    raw_embedding = query.get("theme_embedding")
    if _is_valid_embedding(raw_embedding):
        return [float(v) for v in raw_embedding]

    theme_text = query.get("theme")
    if not isinstance(theme_text, str) or not theme_text.strip():
        return None

    try:
        generated = embed_func(theme_text.strip())
    except Exception as exc:
        logger.warning("search_macro_events: generate query embedding failed: %s", exc)
        return None

    if _is_valid_embedding(generated):
        return [float(v) for v in generated]
    return None


def _get_scene_theme_embedding(
    scene_data: Dict[str, Any],
    embed_func: Callable[[str], List[float]],
) -> Optional[List[float]]:
    raw_embedding = scene_data.get("theme_embedding")
    if _is_valid_embedding(raw_embedding):
        return [float(v) for v in raw_embedding]

    theme_text = scene_data.get("theme")
    if not isinstance(theme_text, str) or not theme_text.strip():
        return None

    # Fallback for legacy scene files without stored theme_embedding.
    try:
        generated = embed_func(theme_text.strip())
    except Exception as exc:
        logger.debug("search_macro_events: generate scene embedding failed: %s", exc)
        return None

    if _is_valid_embedding(generated):
        return [float(v) for v in generated]
    return None


def _load_scene_file(scene_file: Path) -> Optional[Dict[str, Any]]:
    try:
        with open(scene_file, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, dict):
            return data
    except Exception as exc:
        logger.warning("search_macro_events: load scene file failed: %s (%s)", scene_file, exc)
    return None


def _cosine_similarity(vec_a: Any, vec_b: Any) -> float:
    if not _is_valid_embedding(vec_a) or not _is_valid_embedding(vec_b):
        return 0.0
    if len(vec_a) != len(vec_b):
        return 0.0

    dot = 0.0
    norm_a = 0.0
    norm_b = 0.0
    for a, b in zip(vec_a, vec_b):
        a_f = float(a)
        b_f = float(b)
        dot += a_f * b_f
        norm_a += a_f * a_f
        norm_b += b_f * b_f

    if norm_a <= 0.0 or norm_b <= 0.0:
        return 0.0
    return dot / (math.sqrt(norm_a) * math.sqrt(norm_b))


def _is_valid_embedding(value: Any) -> bool:
    if not isinstance(value, list) or not value:
        return False
    return all(isinstance(v, (int, float)) for v in value)


def _safe_float(value: Any, default: float) -> float:
    try:
        return float(value)
    except Exception:
        return float(default)


def _safe_int(value: Any, default: int, minimum: int = 1) -> int:
    try:
        parsed = int(value)
    except Exception:
        parsed = default
    return max(minimum, parsed)
